### ISSUE TITLE
No Start Command

### ISSUE THREAD

**Issue by WaltDisneyWorld** [Cool-Bot-List/Cool-Bot-List#103]
There is no clear start command.

**Comment by CreeperPlanet26** [comment]
The start command is `npm run dev`. This will start the server + bot + client. Make sure u have the .env files. You can join our discord server too. https://discord.gg/akxfPT

**Comment by WaltDisneyWorld** [comment]
Also, do you need help?

**Comment by CreeperPlanet26** [comment]
Yea we are looking for people to help

**Comment by WaltDisneyWorld** [comment]
I can see. Add me.

**Comment by CreeperPlanet26** [comment]
bet u should also join our server its easier to communicate
https://discord.gg/akxfPT

**Comment by WaltDisneyWorld** [comment]
K.

**Comment by WaltDisneyWorld** [comment]
Or
FlexyCaleb#1119

**Comment by WaltDisneyWorld** [comment]
K

**Comment by CreeperPlanet26** [comment]
How did you find our repo?

**Comment by CreeperPlanet26** [comment]
I added you on discord be sure to join the server If you wanna help with this
