### ISSUE TITLE
User Avatar URL generation is messed up

### ISSUE THREAD

**Issue by CreeperPlanet26** [Cool-Bot-List/Cool-Bot-List#43]
When a user is created if they don't have an avatar url, passport returns a link like this that has null in it. https://cdn.discordapp.com/avatars/715269732500111410/null.png?size=2048 

Idk how to fix this. passport should really have a fix. but idk if it is even passport. ig we could check if the avatar url returned from passport contains null and if it does set it to the default avatar link that u found.

**Comment by Maxisthemoose** [comment]
ok

**Comment by CreeperPlanet26** [comment]
Fixed by @Maxisthemoose in Pull request

**Comment by Maxisthemoose** [comment]
Y u mention me

**Comment by CreeperPlanet26** [comment]
Sorry 😥
